// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPtdU_4mKnmtBNVUPEw5HTdvR8dRH01fg',
    appId: '1:97438862818:web:f3f0f392cbf3ac33403dbb',
    messagingSenderId: '97438862818',
    projectId: 'final-project-554f1',
    authDomain: 'final-project-554f1.firebaseapp.com',
    storageBucket: 'final-project-554f1.appspot.com',
    measurementId: 'G-26KXNK7NLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYCeYd-4vkME2LMppqjcnNhZSRNE4-RZ0',
    appId: '1:97438862818:android:dc232dadb5d0432e403dbb',
    messagingSenderId: '97438862818',
    projectId: 'final-project-554f1',
    storageBucket: 'final-project-554f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ_G0IVuhM0sNabRdlEQT6vmDmCSbhdQg',
    appId: '1:97438862818:ios:d71bafd382a9b94f403dbb',
    messagingSenderId: '97438862818',
    projectId: 'final-project-554f1',
    storageBucket: 'final-project-554f1.appspot.com',
    iosBundleId: 'com.example.finalProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ_G0IVuhM0sNabRdlEQT6vmDmCSbhdQg',
    appId: '1:97438862818:ios:994ea4f4a665018d403dbb',
    messagingSenderId: '97438862818',
    projectId: 'final-project-554f1',
    storageBucket: 'final-project-554f1.appspot.com',
    iosBundleId: 'com.example.finalProj.RunnerTests',
  );
}
